package com.example.smarttodo.data

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import java.io.Serializable
import java.util.Date

/**
 * Represents a single task item in the application and the schema for the Room 'tasks' table.
 * Added indices on 'title' and 'createdAt' to improve query performance for searches and ordering
 * when the dataset grows large.
 */
@Entity(
    tableName = "tasks",
    indices = [
        Index(value = ["title"]),
        Index(value = ["createdAt"])
    ]
)
data class Task(
    @PrimaryKey(autoGenerate = true) // Marks 'id' as the primary key, auto-generated by Room.
    val id: Int = 0,
    val title: String,
    val description: String = "",
    val priority: Priority = Priority.LOW,
    val isCompleted: Boolean = false,
    val createdAt: Date = Date(),
    val dueDate: Date? = null,
    val completionDate: Date? = null,
    val hasReminder: Boolean = false,
    val preReminderOffsetMinutes: Int? = null,
    val taskType: TaskType = TaskType.ADMINISTRATIVE,
    val estimatedPomodoros: Int = 0,
    val completedPomodoros: Int = 0,
    val soundUri: String? = null // New field for custom notification sound URI
) : Serializable // Implements Serializable for passing Task objects.

/**
 * Enum representing the priority levels for a [Task].
 */
enum class Priority(val value: Int, val displayName: String) {
    LOW(1, "Low"),
    MEDIUM(2, "Medium"),
    HIGH(3, "High")
}
